apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: etl-enriched-users-analysis
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "owshq/etl-enriched-users-analysis:3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/etl-enriched-users-analysis.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.s3a.endpoint": "http://10.245.43.111"
  driver:
    # cores: 1
    coreRequest: 250m
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: default
  executor:
    # cores: 1
    coreRequest: 250m
    instances: 2
    memory: "512m"
    labels:
      version: 3.0.0
