apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: etl-enriched-users-analysis
  namespace: processing
spec:
  schedule: "@every 60m"
  concurrencyPolicy: Allow
  template:
    type: Python
    mode: cluster
    image: "owshq/etl-enriched-users-analysis:3.1.1"
    imagePullPolicy: Always
    mainApplicationFile: "local:///app/etl-enriched-users-analysis.py"
    sparkVersion: "3.1.1"
    restartPolicy:
      type: Never
    hadoopConf:
      "fs.s3a.endpoint": "http://10.0.72.140"
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      labels:
        version: 3.0.0
      serviceAccount: default
    executor:
      cores: 1
      instances: 3
      memory: "512m"
      labels:
        version: 3.0.0