apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: etl-device-subscription
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "owshq/etl-device-subscription-iceberg:3.2.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/etl-device-subscription.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    "fs.s3a.endpoint": "http://10.245.221.171"
  driver:
    coreRequest: 250m
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: default
  executor:
    coreRequest: 250m
    instances: 3
    memory: "512m"
    labels:
      version: 3.1.1
